name: 'Setup MoltenObsidian CLI (Should be: Successful)'
on:
  - push
  - workflow_dispatch
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MoltenObsidian CLI
        # Run from pushed branch
        uses: Nodsoft/setup-moltenobsidian@${{ github.ref }}

      - name: Run MoltenObsidian CLI & Summarize
        run: |
          echo "### Summary" >> $GITHUB_STEP_SUMMARY
          echo "Successfully installed MoltenObsidian CLI." >> $GITHUB_STEP_SUMMARY
          echo "Installed Version: `$(moltenobsidian --version)`" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Output Help: ```$(moltenobsidian --help)```" >> $GITHUB_STEP_SUMMARY          